theme = "tokyonight_storm"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]
"ret" = ["select_textobject_inner"]

[keys.normal.space]
"w" = ":w"
"q" = ":q"
