vim.loader.enable()
require("config.options")
require("config.diagnostics")
require("config.lazy")
require("config.autocmds")
require("config.keymaps")
require("config.lsp")
require("config.filetype")
