keys:
  - &admin_desktop age168mr8lr4tjxm7hh52yupz5ectc4f3za5euelse83eww7wu9refqq0ns8qg
  - &host_nas age15kjukgaxzqzukd8htu0lpvg29rh5p7dp2d7nawanfrt6tfxuusrsd2fzhl
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_desktop
      - *host_nas
