vim.keymap.set("n", "<leader>gH", "<cmd>DiffviewFileHistory %<cr>", { desc = "File History" })
vim.keymap.set("n", "<leader>gt", "<cmd>DiffviewToggleFiles<cr>", { desc = "Toggle File View" })
vim.keymap.set("n", "<leader>gd", function()
  local branch = vim.fn.input("Diff with origin: ")
  vim.api.nvim_exec2("!git fetch origin " .. branch, {})
  vim.api.nvim_command("DiffviewOpen origin/" .. branch)
end, { desc = "Diff with origin ..." })
vim.keymap.set("n", "<leader>gD", function()
  vim.api.nvim_command("DiffviewOpen " .. vim.fn.input("Diff with: "))
end, { desc = "Diff with ..." })
