require("grapple").setup({ scope = "git" })

vim.keymap.set("n", "<leader>m", "<cmd>Grapple toggle<cr>", { desc = "Mark file" })
vim.keymap.set("n", "<leader>h", "<cmd>Grapple toggle_tags<cr>", { desc = "Toggle mark menu" })
vim.keymap.set("n", "<a-a>", "<cmd>Grapple select index=1<cr>", { desc = "Nav to file 1" })
vim.keymap.set("n", "<a-s>", "<cmd>Grapple select index=2<cr>", { desc = "Nav to file 2" })
vim.keymap.set("n", "<a-d>", "<cmd>Grapple select index=3<cr>", { desc = "Nav to file 3" })
vim.keymap.set("n", "<a-f>", "<cmd>Grapple select index=4<cr>", { desc = "Nav to file 4" })
vim.keymap.set("n", "<a-g>", "<cmd>Grapple select index=5<cr>", { desc = "Nav to file 5" })
vim.keymap.set("n", "<a-A>", "<cmd>Grapple select index=6<cr>", { desc = "Nav to file 6" })
vim.keymap.set("n", "<a-S>", "<cmd>Grapple select index=7<cr>", { desc = "Nav to file 7" })
vim.keymap.set("n", "<a-D>", "<cmd>Grapple select index=8<cr>", { desc = "Nav to file 8" })
vim.keymap.set("n", "<a-F>", "<cmd>Grapple select index=9<cr>", { desc = "Nav to file 9" })
vim.keymap.set("n", "<a-G>", "<cmd>Grapple select index=10<cr>", { desc = "Nav to file 10" })
